import { useEffect, useState } from 'react'
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { useLocalSearchParams, Redirect, router } from 'expo-router'
import { useAuth } from '@/lib/auth-context'
import { acceptBudget, getBudgetsForRequest, rejectBudget } from '@/lib/data'
import { supabase } from '@/lib/supabase'
import type { Budget } from '@/lib/types'

export default function BudgetsScreen(){const{session,profile,loading}=useAuth();const{requestId}=useLocalSearchParams<{requestId?:string}>();const[items,setItems]=useState<Budget[]>([]);const[workshopId,setWorkshopId]=useState('');const[labor,setLabor]=useState('');const[parts,setParts]=useState('');const[days,setDays]=useState('');const[description,setDescription]=useState('');const[saving,setSaving]=useState(false)
useEffect(()=>{if(requestId)getBudgetsForRequest(requestId).then(setItems).catch(e=>Alert.alert('Erro',e.message));if(session&&profile?.role==='oficina')supabase.from('oficinas').select('id').eq('usuario_id',session.user.id).single().then(({data})=>setWorkshopId(data?.id??''))},[requestId,session,profile])
if(!loading&&!session)return<Redirect href="/auth"/>;if(loading||!profile)return<View style={styles.center}><Text style={styles.muted}>Carregando…</Text></View>
async function sendBudget(){if(!requestId||!workshopId||Number(labor)<0||Number(parts)<0)return Alert.alert('Dados inválidos','Informe valores válidos.');setSaving(true);try{const mao=Number(labor)||0,pecas=Number(parts)||0;const{data,error}=await supabase.from('orcamentos').insert({solicitacao_id:requestId,oficina_id:workshopId,valor_mao_obra:mao,valor_pecas:pecas,valor_total:mao+pecas,prazo_dias:Number(days)||null,descricao:description.trim()||null,status:'enviado'}).select().single();if(error)throw error;setItems(v=>[data as Budget,...v]);setLabor('');setParts('');setDays('');setDescription('');Alert.alert('Orçamento enviado','O cliente já pode visualizar sua proposta.')}catch(e){Alert.alert('Não foi possível enviar',e instanceof Error?e.message:'Tente novamente.')}finally{setSaving(false)}}
async function accept(id:string){try{await acceptBudget(id);Alert.alert('Orçamento aceito','O serviço foi criado e já pode ser acompanhado.');router.replace('/services')}catch(e){Alert.alert('Não foi possível aceitar',e instanceof Error?e.message:'Tente novamente.')}}
async function reject(id:string){try{await rejectBudget(id);setItems(v=>v.map(x=>x.id===id?{...x,status:'recusado'}:x))}catch(e){Alert.alert('Não foi possível recusar',e instanceof Error?e.message:'Tente novamente.')}}
return<ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.container}><Text style={styles.title}>Orçamentos</Text>{profile.role==='oficina'&&requestId&&<View style={styles.form}><Text style={styles.section}>Enviar proposta</Text><View style={styles.row}><TextInput value={labor} onChangeText={setLabor} keyboardType="decimal-pad" placeholder="Mão de obra" placeholderTextColor="#77808C" style={[styles.input,{flex:1}]}/><TextInput value={parts} onChangeText={setParts} keyboardType="decimal-pad" placeholder="Peças" placeholderTextColor="#77808C" style={[styles.input,{flex:1}]}/></View><TextInput value={days} onChangeText={setDays} keyboardType="number-pad" placeholder="Prazo em dias" placeholderTextColor="#77808C" style={styles.input}/><TextInput value={description} onChangeText={setDescription} placeholder="Descrição da proposta" placeholderTextColor="#77808C" multiline style={[styles.input,{minHeight:90,textAlignVertical:'top'}]}/><Pressable disabled={saving} onPress={sendBudget} style={styles.primary}><Text style={styles.primaryText}>{saving?'Enviando…':'Enviar orçamento'}</Text></Pressable></View>}{items.length===0?<Text style={styles.muted}>Nenhum orçamento para esta solicitação.</Text>:items.map(b=><View key={b.id} style={styles.card}><Text style={styles.cardTitle}>R$ {(b.valor_total??(b.valor_mao_obra+b.valor_pecas)).toFixed(2)}</Text><Text style={styles.muted}>Mão de obra: R$ {b.valor_mao_obra.toFixed(2)} • Peças: R$ {b.valor_pecas.toFixed(2)}</Text>{b.prazo_dias&&<Text style={styles.muted}>Prazo: {b.prazo_dias} dias</Text>}{b.descricao&&<Text style={styles.description}>{b.descricao}</Text>}<Text style={styles.status}>{b.status}</Text>{profile.role==='cliente'&&b.status==='enviado'&&<View style={styles.row}><Pressable onPress={()=>accept(b.id)} style={styles.primarySmall}><Text style={styles.primaryText}>Aceitar</Text></Pressable><Pressable onPress={()=>reject(b.id)} style={styles.secondary}><Text style={styles.secondaryText}>Recusar</Text></Pressable></View>}</View>)}</ScrollView>}
const styles=StyleSheet.create({container:{padding:20,gap:12,backgroundColor:'#0B0D10'},title:{fontSize:30,fontWeight:'800',color:'#FFF'},section:{fontSize:18,fontWeight:'800',color:'#FFF'},form:{backgroundColor:'#15181D',borderWidth:1,borderColor:'#292F38',borderRadius:16,padding:16,gap:10},row:{flexDirection:'row',gap:8,alignItems:'center'},input:{color:'#FFF',backgroundColor:'#0F1216',borderColor:'#303743',borderWidth:1,borderRadius:12,padding:13},primary:{backgroundColor:'#FFF',borderRadius:12,padding:14,alignItems:'center'},primarySmall:{backgroundColor:'#FFF',borderRadius:10,paddingHorizontal:14,paddingVertical:11},primaryText:{color:'#0B0D10',fontWeight:'800'},secondary:{borderColor:'#3A424D',borderWidth:1,borderRadius:10,paddingHorizontal:14,paddingVertical:11},secondaryText:{color:'#FFF',fontWeight:'700'},card:{backgroundColor:'#15181D',borderWidth:1,borderColor:'#292F38',borderRadius:16,padding:16,gap:7},cardTitle:{color:'#FFF',fontSize:22,fontWeight:'800'},muted:{color:'#A9B0BA',lineHeight:21},description:{color:'#D9DEE5',lineHeight:21},status:{color:'#B7C0CB',fontWeight:'800',textTransform:'capitalize'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#0B0D10'}})
