import { useEffect, useRef, useState } from 'react'
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Redirect, useLocalSearchParams } from 'expo-router'
import { useAuth } from '@/lib/auth-context'
import { getMessages, sendMessage } from '@/lib/data'
import { supabase } from '@/lib/supabase'
import type { Message } from '@/lib/types'

export default function ChatScreen(){const{session,profile,loading}=useAuth();const{requestId}=useLocalSearchParams<{requestId?:string}>();const[messages,setMessages]=useState<Message[]>([]);const[text,setText]=useState('');const[busy,setBusy]=useState(false);const scroll=useRef<ScrollView>(null);useEffect(()=>{if(!requestId)return;getMessages(requestId).then(setMessages).catch(e=>Alert.alert('Erro',e.message));const channel=supabase.channel(`messages:${requestId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'mensagens',filter:`solicitacao_id=eq.${requestId}`},payload=>setMessages(v=>v.some(m=>m.id===payload.new.id)?v:[...v,payload.new as Message])).subscribe();return()=>{supabase.removeChannel(channel)}},[requestId]);if(!loading&&!session)return<Redirect href="/auth"/>;if(loading||!profile||!requestId)return<View style={styles.center}><Text style={styles.muted}>Carregando…</Text></View>;const currentUserId=session.user.id;async function send(){if(!requestId||!text.trim()||busy)return;setBusy(true);try{const sent=await sendMessage(currentUserId,requestId,text);setMessages(v=>v.some(m=>m.id===sent.id)?v:[...v,sent]);setText('')}catch(e){Alert.alert('Não foi possível enviar',e instanceof Error?e.message:'Tente novamente.')}finally{setBusy(false)}}return<View style={styles.container}><ScrollView ref={scroll} contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.messages} onContentSizeChange={()=>scroll.current?.scrollToEnd({animated:true})}>{messages.map(m=><View key={m.id} style={[styles.bubble,m.remetente_id===currentUserId&&styles.mine]}><Text style={styles.message}>{m.conteudo}</Text><Text style={styles.time}>{new Date(m.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</Text></View>)}</ScrollView><View style={styles.composer}><TextInput value={text} onChangeText={setText} placeholder="Digite uma mensagem" placeholderTextColor="#77808C" style={styles.input}/><Pressable onPress={send} disabled={busy||!text.trim()} style={styles.send}><Text style={styles.sendText}>Enviar</Text></Pressable></View></View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#0B0D10'},messages:{padding:16,gap:9},bubble:{alignSelf:'flex-start',maxWidth:'82%',backgroundColor:'#171A20',borderRadius:15,padding:12,gap:4},mine:{alignSelf:'flex-end',backgroundColor:'#EDEFF2'},message:{color:'#FFF',fontSize:15,lineHeight:21},time:{color:'#8D96A2',fontSize:11},composer:{flexDirection:'row',gap:8,padding:12,borderTopWidth:1,borderColor:'#292F38'},input:{flex:1,color:'#FFF',backgroundColor:'#15181D',borderWidth:1,borderColor:'#303743',borderRadius:12,paddingHorizontal:13},send:{backgroundColor:'#FFF',borderRadius:12,justifyContent:'center',paddingHorizontal:15},sendText:{color:'#0B0D10',fontWeight:'800'},muted:{color:'#A9B0BA'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#0B0D10'}})
