import { useCallback, useEffect, useState } from 'react'
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native'
import { Link, Redirect } from 'expo-router'
import { useAuth } from '@/lib/auth-context'
import { getRequests } from '@/lib/data'
import type { Request } from '@/lib/types'

const statusLabel: Record<Request['status'], string> = { aberta:'Aberta', recebendo_orcamentos:'Recebendo orçamentos', orcamento_aceito:'Orçamento aceito', em_servico:'Em serviço', concluida:'Concluída', cancelada:'Cancelada' }
export default function RequestsScreen(){const{session,profile,loading}=useAuth();const[items,setItems]=useState<Request[]>([]);const[refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>{if(!session||!profile)return;try{setItems(await getRequests(session.user.id,profile.role))}catch(e){Alert.alert('Erro',e instanceof Error?e.message:'Não foi possível carregar.')}},[session,profile]);useEffect(()=>{load()},[load]);if(!loading&&!session)return<Redirect href="/auth"/>;if(loading||!profile)return<View style={styles.center}><Text style={styles.muted}>Carregando…</Text></View>;return<ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false)}}/>} contentContainerStyle={styles.container}><Text style={styles.title}>{profile.role==='oficina'?'Solicitações disponíveis':'Minhas solicitações'}</Text>{items.length===0?<View style={styles.empty}><Text style={styles.cardTitle}>Nenhuma solicitação</Text><Text style={styles.muted}>{profile.role==='oficina'?'Quando houver pedidos compatíveis, eles aparecerão aqui.':'Crie sua primeira solicitação para começar.'}</Text></View>:items.map(item=><View key={item.id} style={styles.card}><Text style={styles.cardTitle}>{item.titulo}</Text><Text style={styles.muted}>{item.cidade} / {item.estado} • {item.urgencia}</Text><Text style={styles.description}>{item.descricao}</Text><View style={styles.actions}><Link href={`/budgets?requestId=${item.id}`} asChild><Pressable style={styles.action}><Text style={styles.actionText}>Orçamentos</Text></Pressable></Link><Link href={`/chat?requestId=${item.id}`} asChild><Pressable style={styles.action}><Text style={styles.actionText}>Chat</Text></Pressable></Link></View><Text style={styles.status}>{statusLabel[item.status]}</Text></View>)}</ScrollView>}
const styles=StyleSheet.create({container:{padding:20,gap:12,backgroundColor:'#0B0D10'},title:{fontSize:30,fontWeight:'800',color:'#FFF',marginBottom:4},card:{backgroundColor:'#15181D',borderColor:'#292F38',borderWidth:1,borderRadius:16,padding:16,gap:8},cardTitle:{color:'#FFF',fontSize:18,fontWeight:'800'},muted:{color:'#A9B0BA',lineHeight:21},description:{color:'#D9DEE5',lineHeight:21},actions:{flexDirection:'row',gap:8,marginTop:4},action:{borderWidth:1,borderColor:'#39414D',borderRadius:10,paddingHorizontal:13,paddingVertical:10},actionText:{color:'#FFF',fontWeight:'700'},status:{color:'#B7C0CB',fontWeight:'800',fontSize:13},empty:{padding:20,borderRadius:16,borderWidth:1,borderColor:'#292F38',gap:8},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#0B0D10'}})
