import { useCallback, useEffect, useState } from 'react'
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native'
import { Redirect } from 'expo-router'
import { useAuth } from '@/lib/auth-context'
import { getServices, updateService } from '@/lib/data'
import type { Service } from '@/lib/types'

const labels:Record<Service['status'],string>={aguardando:'Aguardando',agendado:'Agendado',em_andamento:'Em andamento',aguardando_peca:'Aguardando peça',concluido:'Concluído',cancelado:'Cancelado'}
export default function ServicesScreen(){const{session,profile,loading}=useAuth();const[items,setItems]=useState<Service[]>([]);const[refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>{if(!session||!profile)return;try{setItems(await getServices(session.user.id,profile.role))}catch(e){Alert.alert('Erro',e instanceof Error?e.message:'Não foi possível carregar.')}},[session,profile]);useEffect(()=>{load()},[load]);if(!loading&&!session)return<Redirect href="/auth"/>;if(loading||!profile)return<View style={styles.center}><Text style={styles.muted}>Carregando…</Text></View>;async function change(id:string,status:Service['status']){try{const updated=await updateService(id,status);setItems(v=>v.map(x=>x.id===id?updated:x))}catch(e){Alert.alert('Não foi possível atualizar',e instanceof Error?e.message:'Tente novamente.')}}return<ScrollView contentInsetAdjustmentBehavior="automatic" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false)}}/>} contentContainerStyle={styles.container}><Text style={styles.title}>Serviços</Text>{items.length===0?<Text style={styles.muted}>Nenhum serviço ativo ainda.</Text>:items.map(s=><View key={s.id} style={styles.card}><Text style={styles.cardTitle}>{labels[s.status]}</Text><Text style={styles.muted}>Atualizado em {new Date(s.updated_at).toLocaleString('pt-BR')}</Text>{s.observacoes&&<Text style={styles.description}>{s.observacoes}</Text>}{profile.role==='oficina'&&s.status!=='concluido'&&s.status!=='cancelado'&&<View style={styles.row}>{(['agendado','em_andamento','aguardando_peca','concluido'] as Service['status'][]).map(status=><Pressable key={status} onPress={()=>change(s.id,status)} style={styles.chip}><Text style={styles.chipText}>{labels[status]}</Text></Pressable>)}</View>}</View>)}</ScrollView>}
const styles=StyleSheet.create({container:{padding:20,gap:12,backgroundColor:'#0B0D10'},title:{fontSize:30,fontWeight:'800',color:'#FFF'},card:{backgroundColor:'#15181D',borderWidth:1,borderColor:'#292F38',borderRadius:16,padding:16,gap:8},cardTitle:{color:'#FFF',fontSize:19,fontWeight:'800'},muted:{color:'#A9B0BA',lineHeight:21},description:{color:'#D9DEE5'},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},chip:{borderWidth:1,borderColor:'#3A424D',borderRadius:10,paddingHorizontal:11,paddingVertical:9},chipText:{color:'#FFF',fontWeight:'700'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#0B0D10'}})
